### ISSUE TITLE
Read the Matroska specification

### ISSUE THREAD

**Issue by lu-zero** [rust-av/matroska#3]
[matroska specification](https://tools.ietf.org/html/draft-lhomme-cellar-matroska-04)
[main repository](https://github.com/Matroska-Org/matroska-specification)

**Comment by robUx4** [comment]
Since you asked about adding customs elements in the file, you might be interresed in this:
https://github.com/Matroska-Org/ebml-specification/pull/181

It's losely defined, on purpose. But you can signal that the files you create contain your extended elements and a software that is aware of that may know how to interpret them (you get free versioning of your elements).
