### ISSUE TITLE
Unable to parse some ebml headers

### ISSUE THREAD

**Issue by Luni-4** [rust-av/matroska#76]
`ebml_header` function assumes that there are only some kind of IDs or optionally one void. There can be other IDs and multiple voids though. This problem is being repeated in many places in the code 

Many of the IDs that are currently considered mandatory are probably actually optional (like the crop ones in video). That should be checked against the spec.

**Comment by FreezyLemon** [comment]
I tried demuxing some of the [official matroska test files](https://www.matroska.org/downloads/test_suite.html) and it quickly shows problems, even on the first (supposedly simple) file:

Apparently, the header does not include EBMLVersion, EBMLReadVersion, EBMLMaxIdLength or EBMLMaxSizeLength. This is even though [all 4 elements](https://www.rfc-editor.org/rfc/rfc8794.html#name-ebmlversion-element) seem to have a "minOccurs" of 1 in the RFC. I can see a few things happening here:

1. I'm misinterpreting the spec
2. The parser has a bug. mkvinfo does not show any EBMLVersion information either though, and I'm not sure how to 100% verify this.
3. The RFC is just generally ignored on this because there is only one EBML version "out in the wild"

Just as an aside, the DocType, DocTypeVersion and DocTypeReadVersion seem to be set correctly. Also, it might be nice to have some better errors in the debug build (e.g. giving us the ID of the element where parsing went wrong). Though I'm probably not sure if this is possible without worsening the parsing performance.

**Comment by FreezyLemon** [comment]
Aha! That was actually rather easy to find in the [spec](https://www.rfc-editor.org/rfc/rfc8794.html#name-minoccurs):

> EBML Elements with minOccurs set to "1" that also have a default value (see [Section 11.1.6.8](https://www.rfc-editor.org/rfc/rfc8794.html#default)) declared are not REQUIRED to be stored but are REQUIRED to be interpreted; see [Section 11.1.19](https://www.rfc-editor.org/rfc/rfc8794.html#note-on-the-use-of-default-attributes-to-define-mandatory-ebml-elements).

**Comment by Luni-4** [comment]
Thank you @FreezyLemon for your analysis!

It would be helpful to add official matroska files to our testsuite and check that everything works correctly. Unfortunately I don't have much time to look at this crate right now, but PR are always accepted :)

**Comment by FreezyLemon** [comment]
I think the two big problems (voids, header elements being optional) have been solved.
By "other IDs", do you mean finding Element IDs that we don't know or don't expect in the header?

**Comment by FreezyLemon** [comment]
Just tested it again on `master`, and it looks like everything's working :+1:
